# Generated by Django 6.0.6 on 2026-06-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsForTechs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('rust', 'Rust')])),
                ('pythonFrameWork', models.CharField(choices=[('django', 'Django'), ('flask', 'Flask'), ('fastapi', 'FastAPI')])),
                ('javascriptFrameWork', models.CharField(choices=[('react', 'React'), ('nodejs', 'Node.js'), ('vue', 'Vue.js')])),
                ('javaFrameWork', models.CharField(choices=[('spring_boot', 'Spring Boot'), ('jakarta_ee', 'Jakarta EE')])),
                ('rustFrameWork', models.CharField(choices=[('actix_web', 'Actix Web'), ('axum', 'Axum')])),
                ('jobField', models.CharField(choices=[('full_stack', 'Full Stack Developer'), ('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('mobile', 'Mobile App Developer'), ('devops', 'DevOps / Cloud Engineer'), ('data_science', 'Data Scientist / AI Engineer'), ('cybersecurity', 'Cybersecurity Specialist'), ('ui_ux', 'UI/UX Designer'), ('qa_testing', 'QA / Test Engineer'), ('product_manager', 'Product Manager')])),
            ],
        ),
    ]
