# Generated by Django 6.0.6 on 2026-06-29 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterViewQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('topic', models.CharField(choices=[('core_concepts', 'Core Concepts'), ('practical', 'Practical / Coding'), ('system_design', 'System Design'), ('best_practices', 'Best Practices'), ('debugging', 'Debugging'), ('behavioral', 'Behavioral')], default='core_concepts', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('expected_keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InterViewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('programming', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('java', 'Java'), ('rust', 'Rust')])),
                ('pythonFrameWork', models.CharField(choices=[('django', 'Django'), ('flask', 'Flask'), ('fastapi', 'FastAPI')])),
                ('javascriptFrameWork', models.CharField(choices=[('react', 'React'), ('nodejs', 'Node.js'), ('vue', 'Vue.js')])),
                ('javaFrameWork', models.CharField(choices=[('spring_boot', 'Spring Boot'), ('jakarta_ee', 'Jakarta EE')])),
                ('rustFrameWork', models.CharField(choices=[('actix_web', 'Actix Web'), ('axum', 'Axum')])),
                ('jobField', models.CharField(choices=[('full_stack', 'Full Stack Developer'), ('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('mobile', 'Mobile App Developer'), ('devops', 'DevOps / Cloud Engineer'), ('data_science', 'Data Scientist / AI Engineer'), ('cybersecurity', 'Cybersecurity Specialist'), ('ui_ux', 'UI/UX Designer'), ('qa_testing', 'QA / Test Engineer'), ('product_manager', 'Product Manager')])),
                ('total_questions', models.PositiveIntegerField(default=10)),
                ('status', models.CharField(choices=[('beginner', 'Beginner'), ('intermidiate', 'Intermidiate'), ('professional', 'professional')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='OptionsForTechs',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='dashboard.interviewquestions'),
        ),
        migrations.AddField(
            model_name='interviewquestions',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dashboard.interviewsession'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewquestions',
            unique_together={('session', 'order')},
        ),
    ]
